api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        multipart: ['multipart/form-data']
        json: ['application/json']
        jsonld: ['application/ld+json']
    use_symfony_listeners: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        # validator:
        #     legacy_validation_exception: true
    
